# Generated by Django 4.1.5 on 2023-01-25 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trasation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('store_owner', models.CharField(max_length=30)),
                ('store_name', models.CharField(max_length=30)),
                ('recipient_cpf', models.CharField(max_length=11)),
                ('card', models.CharField(max_length=12)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='trasation.trasation')),
            ],
        ),
    ]
