# Generated by Django 4.1.5 on 2023-01-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trasation',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.IntegerField(unique=True)),
                ('description', models.TextField(unique=True)),
                ('nature', models.TextField()),
                ('signal', models.TextField()),
            ],
        ),
    ]
